# DO NOT CHANGE the "init" and "install" sections below

# AppVeyor config for R package quantdr

image: Visual Studio 2022

environment:
  R_HOME: 'C:\Program Files\R\R-4.3.1'
  PATH: 'C:\Program Files\R\R-4.3.1\bin\x64;{PATH}'

install:
  # Install R 4.3.1
  - choco install r.project --version=4.3.1 -y
  - refreshenv

  # Check Rscript version to confirm setup
  - Rscript --version

  # Install remotes package to handle dependencies
  - Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org')"

  # Install package dependencies
  - Rscript -e "remotes::install_deps(dependencies=TRUE)"

build_script:
  # Build and check the package, adjust the tarball name if needed
  - R CMD build .
  - SET PKG_TARBALL=$(Rscript -e "cat(list.files(pattern='quantdr_.*\\.tar\\.gz'))")
  - R CMD check --no-manual --as-cran %PKG_TARBALL%
