# DO NOT CHANGE the "init" and "install" sections below

build: off

environment:
  matrix:
    - R_VERSION: release
    - R_VERSION: devel

install:
  - ps: |
      choco install r.project -y
      RefreshEnv
      $env:PATH = "$($env:ProgramFiles)\R\R-%R_VERSION%\bin\x64;" + $env:PATH
  - ps: |
      Invoke-WebRequest -Uri https://github.com/r-lib/remotes/raw/main/install-github.R -OutFile install-github.R
      Rscript install-github.R
      Rscript -e "remotes::install_deps(dependencies = TRUE)"

build_script:
  - Rscript -e "devtools::check()"

artifacts:
  - path: '*.Rcheck\**\*'
    name: RCheckResults
