# DO NOT CHANGE the "init" and "install" sections below

version: 1.0.{build}

image: Visual Studio 2019

environment:
  R_VERSION: '4.3.1'

install:
  - choco install r.project -version %R_VERSION% -y
  - refreshenv

build_script:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
  - Rscript -e 'devtools::check()'

test_script:
  - Rscript -e 'devtools::test()'

