# DO NOT CHANGE the "init" and "install" sections below

# Use Visual Studio 2022 image with R installed
image: Visual Studio 2022

# Set environment variable to add Rscript to PATH
environment:
  PATH:
    - C:\Program Files\R\R-4.3.1\bin\x64
    - C:\Program Files\R\R-4.3.1\bin

install:
  # Install remotes package for dependency installation
  - Rscript -e "install.packages('remotes', repos='https://cran.r-project.org')"
  # Install all package dependencies from DESCRIPTION
  - Rscript -e "remotes::install_deps(dependencies=TRUE)"

build_script:
  # Diagnostic: check that Rscript is found and print version
  - where Rscript
  - Rscript --version

  # Build source package tarball
  - R CMD build .

  # Run R CMD check on the built package with no manual and as CRAN
  - >
    R CMD check --no-manual --as-cran *.tar.gz

artifacts:
  - path: '*.tar.gz'
